# Nixpacks configuration for Railway deployment
# Specifies Node.js 22 (no build dependencies needed with @libsql/client)

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

